### ISSUE TITLE
能否提供一个Socket报文规范呢

### ISSUE THREAD

**Issue by small-carbon** [chicc999/iris#1]
能否提供一个Socket报文规范呢

**Comment by chicc999** [comment]
## 通信协议格式
具体通信指令分为 header 和 body 两部分。其中 header 为基类 command 中固定字段，body 中为具体命令自定义字段
totalLength | header Length | header content | body length | body content
* totalLength：4字节，后面四部分的总长度
* header Length: 4字节，Command 中header长度，即 header content 长度
* header content: header的实际内容
* body length ：4字节，Command 中body长度，即 body content 长度
* body content：body 实际内容

具体的通信指令的序列化和反序列化，在每个 command 的子类里由自己实现
